# Generated by Django 4.0.5 on 2022-07-06 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_auth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.phoneauth'),
        ),
    ]
