# Generated by Django 4.0.5 on 2022-07-06 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_auth',
            field=models.ForeignKey(db_column='phone_auths', on_delete=django.db.models.deletion.CASCADE, to='users.phoneauth'),
        ),
    ]
